name: Docker Image CI

on:
  release:
    types: [published]

env:
  DOCKERHUB_REGISTRY: nntoan
  DOCKERHUB_REPOSITORY: elasticsearch

jobs:
  deploy:
    name: Deploying image to DockerHub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master
      
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to DockerHub
      id: login-dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push
      id: build-and-push
      env:
        IMAGE_TAG: ${{ steps.vars.outputs.tag }}
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: $DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY:$IMAGE_TAG
